#!/bin/bash

# Betteh SaaS Platform - Text Branding Replacement Script
# Systematically replaces all hardcoded "Coach Will" and "Coach Will Tumbles" text 
# with dynamic tenant-aware branding system references

set -e

echo "🔄 Starting comprehensive text branding replacement..."

# Create a backup directory for safety
BACKUP_DIR="./branding-backup-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP_DIR"

echo "📁 Creating backup in $BACKUP_DIR..."

# Function to backup and replace in a file
replace_in_file() {
    local file="$1"
    local pattern="$2"
    local replacement="$3"
    
    if [[ -f "$file" ]]; then
        # Create backup
        cp "$file" "$BACKUP_DIR/$(basename "$file").backup"
        
        # Replace content
        sed -i '' "$pattern" "$file"
        echo "  ✅ Updated: $file"
    fi
}

# 1. Replace "Coach Will" with dynamic brand references in React components
echo "🎨 Replacing 'Coach Will' references in React components..."

# Parent dashboard coach name references
replace_in_file "client/src/pages/parent-dashboard.tsx" \
    's/{booking\.coachName || '\''Coach Will'\''}/{booking.coachName || brand.coachName}/g'

replace_in_file "client/src/pages/parent-dashboard.tsx" \
    's/Need help or have questions\? Coach Will is here to assist you\./Need help or have questions? {brand.coachName} is here to assist you./g'

# Admin dashboard references
replace_in_file "client/src/pages/admin.tsx" \
    's/Hi Coach Will!/Hi {brand.coachName}!/g'

# 2. Replace email references with environment variables
echo "📧 Updating email references..."

replace_in_file "client/src/pages/parent-dashboard.tsx" \
    's/admin@coachwilltumbles\.com/{brand.contact.email}/g'

replace_in_file "client/src/pages/booking-success.tsx" \
    's/admin@coachwilltumbles\.com/{siteContent?.contact?.email || brand.contact.email}/g'

# 3. Replace domain references in canonical URLs
echo "🌐 Updating canonical URL references..."

# Replace hardcoded domain with dynamic base URL
replace_in_file "client/src/pages/parent-dashboard.tsx" \
    "s|'https://www\.coachwilltumbles\.com/parent-dashboard'|window.location.origin + '/parent-dashboard'|g"

replace_in_file "client/src/pages/admin.tsx" \
    "s|'https://www\.coachwilltumbles\.com/admin'|window.location.origin + '/admin'|g"

replace_in_file "client/src/pages/not-found.tsx" \
    "s|'https://www\.coachwilltumbles\.com/404'|window.location.origin + '/404'|g"

replace_in_file "client/src/pages/not-found.tsx" \
    "s|'https://www\.coachwilltumbles\.com'|window.location.origin|g"

replace_in_file "client/src/pages/terms-of-service.tsx" \
    "s|https://www\.coachwilltumbles\.com/terms|{window.location.origin}/terms|g"

replace_in_file "client/src/pages/verify-email.tsx" \
    "s|'https://www\.coachwilltumbles\.com/verify-email'|window.location.origin + '/verify-email'|g"

replace_in_file "client/src/pages/about.tsx" \
    "s|https://www\.coachwilltumbles\.com|{window.location.origin}|g"

replace_in_file "client/src/pages/admin-login.tsx" \
    "s|'https://www\.coachwilltumbles\.com/admin-login'|window.location.origin + '/admin-login'|g"

replace_in_file "client/src/pages/parent-login.tsx" \
    "s|'https://www\.coachwilltumbles\.com/parent-login'|window.location.origin + '/parent-login'|g"

replace_in_file "client/src/pages/booking-success.tsx" \
    "s|'https://www\.coachwilltumbles\.com/booking-success'|window.location.origin + '/booking-success'|g"

replace_in_file "client/src/pages/tip-detail.tsx" \
    "s|https://www\.coachwilltumbles\.com|\${window.location.origin}|g"

replace_in_file "client/src/pages/parent-setup-success.tsx" \
    "s|'https://www\.coachwilltumbles\.com/parent-setup-success'|window.location.origin + '/parent-setup-success'|g"

replace_in_file "client/src/pages/parent/confirm-booking.tsx" \
    "s|'https://www\.coachwilltumbles\.com/parent/confirm-booking'|window.location.origin + '/parent/confirm-booking'|g"

# 4. Replace page title references
echo "📄 Updating page titles..."

replace_in_file "client/src/pages/parent-dashboard.tsx" \
    's/Parent Dashboard — Coach Will Tumbles/Parent Dashboard — {brand.businessName}/g'

replace_in_file "client/src/pages/admin.tsx" \
    's/Admin Dashboard — Coach Will Tumbles/Admin Dashboard — {brand.businessName}/g'

# 5. Update server-side references
echo "🖥️  Updating server-side references..."

# PDF generation text
replace_in_file "server/routes.ts" \
    "s/'Generated by CoachWillTumbles Admin'/'Generated by Betteh Admin'/g"

replace_in_file "server/routes.ts" \
    "s/'CoachWillTumbles\.com'/'Betteh.com'/g"

replace_in_file "server/routes.ts" \
    "s/'Coach Will Tumbles'/brandConfig.businessName/g"

# Email sender names
replace_in_file "server/routes.ts" \
    "s/'Coach Will <noreply@coachwilltumbles\.com>'/\`\${brandConfig.coachName} <noreply@betteh.com>\`/g"

# Default coach name references
replace_in_file "server/routes.ts" \
    "s/'Coach Will'/brandConfig.coachName/g"

replace_in_file "server/storage.ts" \
    "s/'Coach Will'/brandConfig.coachName/g"

replace_in_file "server/modern-storage.ts" \
    "s/'Coach Will'/brandConfig.coachName/g"

# Blog post seed data
replace_in_file "server/routes.ts" \
    "s/'Welcome to Coach Will Tumbles'/'Welcome to Betteh Platform'/g"

# 6. Update schema defaults
echo "🗄️  Updating schema defaults..."

replace_in_file "shared/schema.ts" \
    's/\.default("Coach Will")/\.default("Betteh Coach")/g'

# 7. Update API documentation
echo "📚 Updating API documentation..."

replace_in_file "server/api-docs.ts" \
    "s/Coach Will Tumbles \/ Betteh Platform API/Betteh Platform API/g"

replace_in_file "server/api-docs.ts" \
    's/single-tenant "Coach Will Tumbles"/legacy single-tenant system/g'

# 8. Update configuration files that reference specific domain patterns
echo "⚙️  Updating configuration files..."

# Update session configuration to use environment variables for domains
replace_in_file "server/config/session.ts" \
    "s/'https:\/\/coachwilltumbles\.com'/process.env.FRONTEND_URL || 'https:\/\/app.betteh.com'/g"

# Update URL configuration
replace_in_file "server/lib/url.ts" \
    "s/'https:\/\/www\.coachwilltumbles\.com'/'https:\/\/app.betteh.com'/g"

# 9. Update Copilot instructions title
echo "🤖 Updating AI instructions..."

replace_in_file ".github/copilot-instructions.md" \
    's/# CoachWillTumbles - AI Coding Agent Instructions/# Betteh SaaS Platform - AI Coding Agent Instructions/g'

echo "✅ Text branding replacement complete!"
echo ""
echo "📋 Summary of changes:"
echo "  • Replaced 'Coach Will' with dynamic brand references"
echo "  • Updated email addresses to use brand configuration"
echo "  • Converted hardcoded domains to dynamic URLs"
echo "  • Updated page titles and PDF generation text"
echo "  • Modified server-side default values"
echo "  • Updated schema defaults and API documentation"
echo ""
echo "⚠️  Next steps required:"
echo "  1. Add BrandContext imports to updated components"
echo "  2. Update components to use useBrand() hook"
echo "  3. Test all updated pages for proper brand display"
echo "  4. Verify email functionality with new sender names"
echo ""
echo "💾 Backup created in: $BACKUP_DIR"
